name: Conda Tests

on:
  workflow_run:
    workflows: ["Build Wheels"]
    types:
      - completed


jobs:
  test_conda_build:
    name: Conda wheel test mac
    runs-on: macos-latest
    defaults:
      run:
        shell: bash -l {0}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
        with:
          submodules: true

      - uses: conda-incubator/setup-miniconda@v2
        with:
          auto-update-conda: true
          channels: conda-forge
          # Python 3.9 does not support all libs we need in swmm-python
          python-version: 3.8

      - name: Install required system packages
        run: brew install swig ninja

      - name: Install requirements
        run: |
          cd swmm-toolkit
          conda create -n test-env pip
          conda activate test-env
          pip install -r build-requirements.txt
          python setup.py bdist_wheel
          conda deactivate

      - name: Test wheel
        run: |
          cd swmm-toolkit
          conda activate test-env
          pip install -r test-requirements.txt
          python -m pip install --no-index --find-links=./dist swmm_toolkit
          pytest
          conda deactivate
